project:
  type: website
  output-dir: ../docs
  resources:
    - /papers/images/2024_ICSE_Doc_Sym.pdf

website:
  title: "Ali Al-Kaswan"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - about.qmd

    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/aalkaswan
      - icon: github
        href: https://github.com/aalkaswan
      - icon: twitter
        href: https://twitter.com/aalkaswan1
      - icon: cloud
        href: https://tryhackme.com/p/aalkaswan
    search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



